repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: docs

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
    -   id: ruff
        args: [ --fix ]
        exclude: ^.*/migrations/.*$
    -   id: ruff-format
        exclude: ^.*/migrations/.*$
-   repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0
    hooks:
    -   id: pydocstyle
